home/urls.py
from django.urls import path
from .views import *
from .apiView import *

urlpatterns = [
    # pages
    path('home/', homepage, name='homepage'),
    path('', loginPage, name='loginPage'),
    path('logout/', user_logout, name='logout'),
    path('postLogin/', postLogin, name='UserLogin'),

    # collection
    path('collection_home/', collection_home, name='collection_home'),
    path('customer_list_admin/', customer_list_admin, name='customer_list_admin'),
    path('customer_list/', customer_list, name='customer_list'),
    path('customer_add/', customer_add, name='customer_add'),
    path('customer_add_admin/', customer_add_admin, name='customer_add_admin'),
    path('sales_add/', sales_add, name='sales_add'),
    path('sales_add_admin/', sales_add_admin, name='sales_add_admin'),
    path('sales_edit_admin/<int:id>/', sales_edit_admin, name='sales_edit_admin'),
    path('sales_list/', sales_list, name='sales_list'),
    path('sales_list_admin/', sales_list_admin, name='sales_list_admin'),
    path('document_list_admin/', document_list_admin, name='document_list_admin'),
    path('report_admin/', report_admin, name='report_admin'),
    path('installment_report_admin/', installment_report_admin, name='installment_report_admin'),

    path('customer_detail/<int:id>/', customer_detail, name='customer_detail'),
    path('customer_detail_admin/<int:id>/', customer_detail_admin, name='customer_detail_admin'),
    path('customer_edit_admin/<int:id>/', customer_edit_admin, name='customer_edit_admin'),
    path('sales_detail/<int:id>/', sales_detail, name='sales_detail'),
    path('installment_list/', installment_list, name='installment_list'),
    path('my_profile/', my_profile, name='my_profile'),

    # admin
    path('my_profile_admin/', my_profile_admin, name='my_profile_admin'),
    path('admin_home/', admin_home, name='admin_home'),
    path('user_list/', user_list, name='user_list'),
    path('product_list/', product_list, name='product_list'),
    path('purchase_list/', purchase_list, name='purchase_list'),
    path('purchase_add/', purchase_add, name='purchase_add'),
    path('supplier_add/', supplier_add, name='supplier_add'),
    path('installment_list_admin/', installment_list_admin, name='installment_list_admin'),
    path('sales_detail_admin/<int:id>/', sales_detail_admin, name='sales_detail_admin'),

    path('login_logout_report_admin/', login_logout_report_admin, name='login_logout_report_admin'),

    # api Staff
    path('api/add_staff_api/', add_staff_api, name='add_staff_api'),
    path('api/delete_staff_user/', delete_staff_user, name='delete_staff_user'),
    path('api/get_staff_user_detail/', get_staff_user_detail, name='get_staff_user_detail'),
    path('api/edit_staff_api/', edit_staff_api, name='edit_staff_api'),
    path('api/StaffUserListJson/', StaffUserListJson.as_view(), name='StaffUserListJson'),

    # api Product
    path('api/list_product_api/', list_product_api, name='list_product_api'),
    path('api/add_product_api/', add_product_api, name='add_product_api'),
    path('api/delete_product/', delete_product, name='delete_product'),
    path('api/get_product_detail/', get_product_detail, name='get_product_detail'),
    path('api/edit_product_api/', edit_product_api, name='edit_product_api'),
    path('api/ProductListJson/', ProductListJson.as_view(), name='ProductListJson'),

    # api Supplier
    path('api/add_supplier_api/', add_supplier_api, name='add_supplier_api'),
    path('api/delete_supplier/', delete_supplier, name='delete_supplier'),
    path('api/get_supplier_detail/', get_supplier_detail, name='get_supplier_detail'),
    path('api/edit_supplier_api/', edit_supplier_api, name='edit_supplier_api'),
    path('api/SupplierListJson/', SupplierListJson.as_view(), name='SupplierListJson'),

    # api purchase

    path('api/add_purchase_api/', add_purchase_api, name='add_purchase_api'),
    path('api/delete_purchase/', delete_purchase, name='delete_purchase'),
    path('api/get_purchase_detail/<int:id>/', get_purchase_detail, name='get_purchase_detail'),
    path('api/PurchaseListJson/', PurchaseListJson.as_view(), name='PurchaseListJson'),

    # api Customer

    path('api/delete_customer_api/', delete_customer_api, name='delete_customer_api'),
    path('api/list_customer_api/', list_customer_api, name='list_customer_api'),
    path('api/add_customer_api/', add_customer_api, name='add_customer_api'),
    path('api/edit_customer_api/', edit_customer_api, name='edit_customer_api'),
    path('api/CustomerListByUserJson/', CustomerListByUserJson.as_view(), name='CustomerListByUserJson'),
    path('api/CustomerListAdminJson/', CustomerListAdminJson.as_view(), name='CustomerListAdminJson'),

    # sales
    path('api/delete_sale_api/', delete_sale_api, name='delete_sale_api'),
    path('api/add_sales_api/', add_sales_api, name='add_sales_api'),
    path('api/add_sales_admin_api/', add_sales_admin_api, name='add_sales_admin_api'),
    path('api/edit_sales_admin_api/', edit_sales_admin_api, name='edit_sales_admin_api'),
    path('api/list_sales_api/', list_sales_api, name='list_sales_api'),
    path('api/change_sales_status/', change_sales_status, name='change_sales_status'),
    path('api/SalesListByUserJson/', SalesListByUserJson.as_view(), name='SalesListByUserJson'),
    path('api/SalesListAdminJson/', SalesListAdminJson.as_view(), name='SalesListAdminJson'),

    # installments
    path('api/InstallmentListByAdminJson/', InstallmentListByAdminJson.as_view(), name='InstallmentListByAdminJson'),
    path('api/InstallmentListByUserJson/', InstallmentListByUserJson.as_view(), name='InstallmentListByUserJson'),
    path('api/delete_installment_api/', delete_installment_api, name='delete_installment_api'),
    path('api/get_installment_detail/', get_installment_detail, name='get_installment_detail'),
    path('api/add_installment_api/', add_installment_api, name='add_installment_api'),
    path('api/add_installment_remark_api/', add_installment_remark_api, name='add_installment_remark_api'),
    path('api/add_new_installment_api/', add_new_installment_api, name='add_new_installment_api'),
    path('api/edit_installment_api/', edit_installment_api, name='edit_installment_api'),

    # report dashboard
    path('api/get_collection_user_report_api/', get_collection_user_report_api, name='get_collection_user_report_api'),
    path('api/get_admin_report_api/', get_admin_report_api, name='get_admin_report_api'),
    path('api/get_last_three_days_collection_report_for_admin_api/',
         get_last_three_days_collection_report_for_admin_api,
         name='get_last_three_days_collection_report_for_admin_api'),
    path('api/get_last_three_days_collection_report_for_user_api/', get_last_three_days_collection_report_for_user_api,
         name='get_last_three_days_collection_report_for_user_api'),
    path('api/get_daily_collections_by_staff/', get_daily_collections_by_staff, name='get_daily_collections_by_staff'),

    # documents
    path('api/add_document_api/', add_document_api, name='add_document_api'),
    path('api/delete_document/', delete_document, name='delete_document'),
    path('api/get_document_detail/', get_document_detail, name='get_document_detail'),
    path('api/edit_document_api/', edit_document_api, name='edit_document_api'),
    path('api/DocumentListAdminJson/', DocumentListAdminJson.as_view(), name='DocumentListAdminJson'),

    # login and logout
    path('api/LoginLogoutListAdminJson/', LoginLogoutListAdminJson.as_view(), name='LoginLogoutListAdminJson'),

    # change password
    path('api/change_password_api/', change_password_api, name='change_password_api'),

    # report Downloads
    path('download_sales_report/', download_sales_report, name='download_sales_report'),
    path('download_installment_report/', download_installment_report, name='download_installment_report'),


    path('compare_money_api/', compare_money_api, name='compare_money_api'),

]

pro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='homeApp')),
    path('admin/', admin.site.urls),
    path('activate/', include(('activation.urls', 'activation'), namespace='activationApp')),
    path('', include('pwa.urls')),
    # path('', include('home.urls', namespace='homeApp')),
    # path('activation/', include('activation.urls', namespace='activationApp')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/templates/home/login.html
{% load static %}
{% load pwa %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,  initial-scale=1.0, maximum-scale=5.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'sw/images/favicon.ico' %}" sizes="any">
    <link rel="apple-touch-icon" href="{% static 'sw/images/apple-touch-icon.png' %}">
    <title>Login</title>
    {% progressive_web_app_meta %}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'cssMain/semantic.min.css' %}">#}
    {#     <script src="{% static 'jsMain/jquery.min.js' %}"></script>#}
    {#    <script src="{% static 'jsMain/semantic.min.js' %}"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.8/semantic.min.css"
          integrity="sha512-pbLYRiE96XJxmJgF8oWBfa9MdKwuXhlV7vgs2LLlapHLXceztfcta0bdeOgA4reIf0WH67ThWzA684JwkM3zfQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.8/semantic.min.js"
            integrity="sha512-t5mAtfZZmR2gl5LK7WEkJoyHCfyzoy10MlerMGhxsXl3J7uSSNTAW6FK/wvGBC8ua9AFazwMaC0LxsMTMiM5gg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'sw/app.js' %}"></script>


    <style>
        body {
            background-color: #ffffff;
        }

        fieldset {
            border: none;
        }

        .container {
            padding-top: 100px;
        }

        .ui.grid {
            display: flex;
            justify-content: center;
        }

        header {
            background-color: #202731;
            color: #ffffff;
            display: block;
            padding: 1em;
            text-align: center;
            font-size: 16px;
        }

        .input-wrapper {
            position: relative;
            display: block;
            margin: 1em auto;
            border-bottom: 1px solid #e91e63;
            border-radius: 3px;
            width: 300px;
            padding-left: 20px;
            font-size: 20px;
        }

        input {
            width: 100%;
            line-height: 1;
            background-color: transparent;
            border: none;
            padding: .6em .5em;
            outline: 0;
            color: white;
        }

        .column_1 {
            width: 300px;
            background-color: #ffffff;
            border-radius: 5px;

        }

        .column_2 {
            width: 300px;
            background-color: #272E38;
            border-radius: 5px;
        }

        button {
            outline: 0;
            font-size: 12px;
            letter-spacing: 0.1em;
            background-color: #e91e63;
            color: #fff;
            border: none;
            border-radius: 3px;
            width: 200px;
            padding: 1.2em 0;
            margin: 4em auto;
            display: block;
            border-top: 2px solid transparent;
            border-bottom: 2px solid transparent;
        }

        hover {
            border-bottom-color: darkgoldenrod;
        }

        p.hd {
            text-align: center;
            font-variant: small-caps;
            font-weight: bold;
            font-family: "Times New Roman", Times, serif;
            font-size: 30px;
            color: #3c3a3a;
        }

        .credit {
            text-align: center;
            font-size: 18px;
            padding-top: 20px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="ui equal width center aligned padded grid">
        <div class="ui raised segment">
            <div class="ui two column centered grid">
                <div class="column_1" style="width: 350px; padding: 05px">
                    <img class="ui centered medium circular image" src="{% static 'sw/images/icon-192.png' %}"
                         style="width: 100px;height: 100px;margin-top: 30px" alt="Logo">
                    <br>
                    <p class="hd">Yelhoumee</p>

                </div>
                <div class="column_2" style="width: 350px; padding: 05px">
                    <form id="userLoginForm" action="{% url 'homeApp:UserLogin' %}" method="post">{% csrf_token %}
                        <div class="login-form-container">
                            <header>LOGIN</header>
                            <fieldset>
                                <div class="input-wrapper">
                                    <input type="text" placeholder="Username" name="userName" id="userName"/>
                                </div>
                                <div class="input-wrapper">
                                    <input type="password" placeholder="Password " name="password" id="password"/>
                                </div>
                                <button style="cursor: pointer" id="continue" type="button" onclick="UserLogin()">
                                    CONTINUE
                                </button>
                            </fieldset>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<p class="credit" style="margin-top: 50px;">Developed by <a href="http://www.zivainfotech.com" target="_blank">Ziva Infotech</a></p>
<script>
    function UserLogin() {
        var username = $('#userName').val();
        var password = $('#password').val();

        if (username === "" || password === "") {


            $('body')
                .toast({
                    class: 'error',
                    message: 'Username and Password is required !'
                })
            ;

        } else {
            data = new FormData();
            data.append('userName', username);
            data.append('password', password);

            $.ajax({
                type: 'post',
                url: '{% url 'homeApp:UserLogin' %}',
                data: data,
                contentType: false,
                cache: false,
                processData: false,


                success: function (response) {
                    if (response.message === 'success') {
                        $('body')
                            .toast({
                                class: 'success',
                                message: 'Login Successful.'
                            });
                        document.location.href = "" + response.data;
                    } else {
                        $('body')
                            .toast({
                                class: 'warning',
                                message: 'Incorrect username or password. Please try again.'
                            })
                        ;

                    }

                    return response;
                },
                error: function () {
                    $('body')
                        .toast({
                            class: 'error',
                            message: 'An error occurred !'
                        })
                    ;
                }
            });
        }
    }
</script>
</body>
</html>

home/templates/home/profile.html
{% extends 'home/admin/index.html' %}
{% load static %}

{% block title %}
    <title>My Profile</title>
{% endblock %}
{% block css %}

{% endblock %}
{% block body %}
    <div class="ui right aligned basic  grid">
        <div class="sixteen wide column">
            <div class="ui  pointing secondary menu">
                <div style="cursor: pointer;" class="item active" data-tab="user"
                >My Profile
                </div>
            </div>

            <div class="ui tab " data-tab="user">

                <div class="row" style="padding-left: 5px; padding-right: 5px">
                    <div class="ui placeholder segment" style="width: 100%;">
                        {% comment %}
            <a href="/ecom/editAccount/" class="editbtn"><i class="edit icon"></i></a>
{% endcomment %}
                        <div class="ui icon header">
                            <div class="inline ">
                                <img class="ui medium circular image tiny centered" id="cImg"
                                     src="{{ instance.photo.medium.url }}">
                            </div>
                            <span id="Name">{{ instance.name|capfirst }} </span>
                        </div>
                        <div class="inline">
                            <span id="username" class="ui text medium grey">{{ instance.username }}</span>
                        </div>
                        <div class="inline">
                            <span id="Phone">{{ instance.phone }}</span>
                        </div>
                        <div class="inline">
                            <span id="address" class="ui text large grey">{{ instance.address|capfirst }} </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

home/templates/home/salesDetail.html
{% extends 'home/collection/indexCollection.html' %}
{% load static %}
{% block title %}
    <title>Sales Detail</title>
{% endblock %}
{% block css %}
{% endblock %}
{% block body %}

    <style>


        #UserTable_length {
            left: 20px;
            position: absolute;
        }

        #UserTable_filter {
            width: 50%;
            float: right;
        }

        .dt-buttons {
            position: absolute;
            left: 174px;
        }

        input[type=search] {
            width: 100px !important;
        }
    </style>

    <div class="ui right aligned basic  grid">
        <div class="sixteen wide column">
            <div class="ui  pointing secondary menu">
                <div style="cursor: pointer;" class="item active" data-tab="user"
                >Sales Detail
                </div>

            </div>
            <div class="ui tab  " data-tab="user" style="padding: 5px;">
                <h5 class="ui horizontal left aligned divider header">
                    <i class="left align icon"></i>
                    Customer Detail
                </h5>
                <div class="ui horizontal cards">
                    <div class="card" style="width: 100%; text-align: left">
                        <div class="image">
                            <img src="{{ instance.customerID.photo.medium.url }}">
                        </div>
                        <div class="content aligned left">
                            <div class="header">{{ instance.customerID.name|capfirst }}</div>
                            <div class="meta">
                                <a> Code: {{ instance.customerID.customerCode }}</a> <br>
                                <a style="color: teal">{{ instance.customerID.phoneNumber }}</a>
                            </div>
                            <div class="description">
                                {{ instance.customerID.address|capfirst }} , {{ instance.customerID.district }}
                            </div>
                            <div class="meta">
                                <a> Added On: {{ instance.customerID.datetime }}</a>
                            </div>
                        </div>
                    </div>

                </div>
                <h5 class="ui horizontal left aligned divider header">
                    <i class="left align icon"></i>
                    Sales Detail
                </h5>
                <div class="ui horizontal cards">
                    <div class="card" style="width: 100%; text-align: left">
                        <div class="image">
                            <img src="{{ instance.deliveryPhoto.medium.url }}">
                        </div>
                        <div class="content aligned left">
                            <div class="header">{{ instance.productName|capfirst }}</div>
                            <div class="meta">
                                <button style="color: Green;margin: 2px;" class="ui mini button"> Total Amount:
                                    ₹ {{ instance.totalAmount }}</button>
                                <button style="color: Green;margin: 2px;" class="ui mini button"> Advance:
                                    ₹ {{ instance.advancePaid }}</button>
                                <button style="color: Green;margin: 2px;" class="ui mini button"> Paid Amount:
                                    ₹ {{ instance.amountPaid }}</button>
                                <button style="color: Green;margin: 2px;" class="ui mini button">
                                    Tenure: {{ instance.tenureInMonth }} Months
                                </button>
                                <button style="color: Green;margin: 2px;" class="ui mini button"> EMI Amount:
                                    ₹ {{ instance.emiAmount }}</button>

                            </div>
                            <div class="description">
                                Installment Start Date: {{ instance.installmentStartDate }}
                            </div>
                            <div class="description">
                                <p>Status:
                                    {% if instance.isClosed == False %}

                                        <span class="ui text red"> Open </span>
                                    {% else %}
                                        <span class="ui text green"> Closed </span>
                                    {% endif %}

                                </p>
                            </div>
                            <div class="meta">
                                <a> Added By: {{ instance.addedBy.name|capfirst }} On {{ instance.datetime }}</a> <br>
                                <a> Assigned To: {{ instance.assignedTo.name|capfirst }} </a>
                            </div>
                        </div>
                    </div>

                </div>
                <h5 class="ui horizontal left aligned divider header">
                    <i class="left align icon"></i>
                    Installment List
                </h5>
                <div style="width: 100%; overflow-x: scroll">
                    <table class="ui unstackable purple table">
                        <thead>
                        <tr>
                            <th>Slno.</th>
                            <th>Inst._Date</th>
                            <th class="right aligned">Paid_Amount</th>
                            <th class="right aligned">Fine_Amount</th>
                            <th>Is_Paid?</th>
                            <th>Is_Reassigned?</th>
                            <th>Collected_On</th>
                            <th>Collected_By</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for installment in installments %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ installment.installmentDate }}</td>
                                <td class="right aligned">{{ installment.amountPaid }}</td>
                                <td class="right aligned">{{ installment.finePaid }}</td>
                                <td>{{ installment.isPaid }}</td>
                                <td>{{ installment.isReassigned }}</td>
                                <td>{{ installment.paymentReceivedOn }}</td>
                                <td>{{ installment.collectedBy }}</td>
                            </tr>
                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

{% block js %}
    <script>


    </script>

{% endblock %}