home/urls.py
from django.urls import path
from .views import *
from .apiView import *

urlpatterns = [
    # pages
    path('home/', homepage, name='homepage'),
    path('', loginPage, name='loginPage'),
    path('logout/', user_logout, name='logout'),
    path('postLogin/', postLogin, name='UserLogin'),

    # collection
    path('collection_home/', collection_home, name='collection_home'),
    path('customer_list_admin/', customer_list_admin, name='customer_list_admin'),
    path('customer_list/', customer_list, name='customer_list'),
    path('customer_add/', customer_add, name='customer_add'),
    path('customer_add_admin/', customer_add_admin, name='customer_add_admin'),
    path('sales_add/', sales_add, name='sales_add'),
    path('sales_add_admin/', sales_add_admin, name='sales_add_admin'),
    path('sales_edit_admin/<int:id>/', sales_edit_admin, name='sales_edit_admin'),
    path('sales_list/', sales_list, name='sales_list'),
    path('sales_list_admin/', sales_list_admin, name='sales_list_admin'),
    path('document_list_admin/', document_list_admin, name='document_list_admin'),
    path('report_admin/', report_admin, name='report_admin'),
    path('installment_report_admin/', installment_report_admin, name='installment_report_admin'),

    path('customer_detail/<int:id>/', customer_detail, name='customer_detail'),
    path('customer_detail_admin/<int:id>/', customer_detail_admin, name='customer_detail_admin'),
    path('customer_edit_admin/<int:id>/', customer_edit_admin, name='customer_edit_admin'),
    path('sales_detail/<int:id>/', sales_detail, name='sales_detail'),
    path('installment_list/', installment_list, name='installment_list'),
    path('my_profile/', my_profile, name='my_profile'),

    # admin
    path('my_profile_admin/', my_profile_admin, name='my_profile_admin'),
    path('admin_home/', admin_home, name='admin_home'),
    path('user_list/', user_list, name='user_list'),
    path('product_list/', product_list, name='product_list'),
    path('purchase_list/', purchase_list, name='purchase_list'),
    path('purchase_add/', purchase_add, name='purchase_add'),
    path('supplier_add/', supplier_add, name='supplier_add'),
    path('installment_list_admin/', installment_list_admin, name='installment_list_admin'),
    path('sales_detail_admin/<int:id>/', sales_detail_admin, name='sales_detail_admin'),

    path('login_logout_report_admin/', login_logout_report_admin, name='login_logout_report_admin'),

    # api Staff
    path('api/add_staff_api/', add_staff_api, name='add_staff_api'),
    path('api/delete_staff_user/', delete_staff_user, name='delete_staff_user'),
    path('api/get_staff_user_detail/', get_staff_user_detail, name='get_staff_user_detail'),
    path('api/edit_staff_api/', edit_staff_api, name='edit_staff_api'),
    path('api/StaffUserListJson/', StaffUserListJson.as_view(), name='StaffUserListJson'),

    # api Product
    path('api/list_product_api/', list_product_api, name='list_product_api'),
    path('api/add_product_api/', add_product_api, name='add_product_api'),
    path('api/delete_product/', delete_product, name='delete_product'),
    path('api/get_product_detail/', get_product_detail, name='get_product_detail'),
    path('api/edit_product_api/', edit_product_api, name='edit_product_api'),
    path('api/ProductListJson/', ProductListJson.as_view(), name='ProductListJson'),

    # api Supplier
    path('api/add_supplier_api/', add_supplier_api, name='add_supplier_api'),
    path('api/delete_supplier/', delete_supplier, name='delete_supplier'),
    path('api/get_supplier_detail/', get_supplier_detail, name='get_supplier_detail'),
    path('api/edit_supplier_api/', edit_supplier_api, name='edit_supplier_api'),
    path('api/SupplierListJson/', SupplierListJson.as_view(), name='SupplierListJson'),

    # api purchase

    path('api/add_purchase_api/', add_purchase_api, name='add_purchase_api'),
    path('api/delete_purchase/', delete_purchase, name='delete_purchase'),
    path('api/get_purchase_detail/<int:id>/', get_purchase_detail, name='get_purchase_detail'),
    path('api/PurchaseListJson/', PurchaseListJson.as_view(), name='PurchaseListJson'),

    # api Customer

    path('api/delete_customer_api/', delete_customer_api, name='delete_customer_api'),
    path('api/list_customer_api/', list_customer_api, name='list_customer_api'),
    path('api/add_customer_api/', add_customer_api, name='add_customer_api'),
    path('api/edit_customer_api/', edit_customer_api, name='edit_customer_api'),
    path('api/CustomerListByUserJson/', CustomerListByUserJson.as_view(), name='CustomerListByUserJson'),
    path('api/CustomerListAdminJson/', CustomerListAdminJson.as_view(), name='CustomerListAdminJson'),

    # sales
    path('api/delete_sale_api/', delete_sale_api, name='delete_sale_api'),
    path('api/add_sales_api/', add_sales_api, name='add_sales_api'),
    path('api/add_sales_admin_api/', add_sales_admin_api, name='add_sales_admin_api'),
    path('api/edit_sales_admin_api/', edit_sales_admin_api, name='edit_sales_admin_api'),
    path('api/list_sales_api/', list_sales_api, name='list_sales_api'),
    path('api/change_sales_status/', change_sales_status, name='change_sales_status'),
    path('api/SalesListByUserJson/', SalesListByUserJson.as_view(), name='SalesListByUserJson'),
    path('api/SalesListAdminJson/', SalesListAdminJson.as_view(), name='SalesListAdminJson'),

    # installments
    path('api/InstallmentListByAdminJson/', InstallmentListByAdminJson.as_view(), name='InstallmentListByAdminJson'),
    path('api/InstallmentListByUserJson/', InstallmentListByUserJson.as_view(), name='InstallmentListByUserJson'),
    path('api/delete_installment_api/', delete_installment_api, name='delete_installment_api'),
    path('api/get_installment_detail/', get_installment_detail, name='get_installment_detail'),
    path('api/add_installment_api/', add_installment_api, name='add_installment_api'),
    path('api/add_installment_remark_api/', add_installment_remark_api, name='add_installment_remark_api'),
    path('api/add_new_installment_api/', add_new_installment_api, name='add_new_installment_api'),
    path('api/edit_installment_api/', edit_installment_api, name='edit_installment_api'),

    # report dashboard
    path('api/get_collection_user_report_api/', get_collection_user_report_api, name='get_collection_user_report_api'),
    path('api/get_admin_report_api/', get_admin_report_api, name='get_admin_report_api'),
    path('api/get_last_three_days_collection_report_for_admin_api/',
         get_last_three_days_collection_report_for_admin_api,
         name='get_last_three_days_collection_report_for_admin_api'),
    path('api/get_last_three_days_collection_report_for_user_api/', get_last_three_days_collection_report_for_user_api,
         name='get_last_three_days_collection_report_for_user_api'),
    path('api/get_daily_collections_by_staff/', get_daily_collections_by_staff, name='get_daily_collections_by_staff'),

    # documents
    path('api/add_document_api/', add_document_api, name='add_document_api'),
    path('api/delete_document/', delete_document, name='delete_document'),
    path('api/get_document_detail/', get_document_detail, name='get_document_detail'),
    path('api/edit_document_api/', edit_document_api, name='edit_document_api'),
    path('api/DocumentListAdminJson/', DocumentListAdminJson.as_view(), name='DocumentListAdminJson'),

    # login and logout
    path('api/LoginLogoutListAdminJson/', LoginLogoutListAdminJson.as_view(), name='LoginLogoutListAdminJson'),

    # change password
    path('api/change_password_api/', change_password_api, name='change_password_api'),

    # report Downloads
    path('download_sales_report/', download_sales_report, name='download_sales_report'),
    path('download_installment_report/', download_installment_report, name='download_installment_report'),


    path('compare_money_api/', compare_money_api, name='compare_money_api'),

]

pro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='homeApp')),
    path('admin/', admin.site.urls),
    path('activate/', include(('activation.urls', 'activation'), namespace='activationApp')),
    path('', include('pwa.urls')),
    # path('', include('home.urls', namespace='homeApp')),
    # path('activation/', include('activation.urls', namespace='activationApp')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/templates/home/admin/ReportInstallmentsByAdmin.html
{% extends 'home/admin/index.html' %}
{% load static %}
{% block title %}
    <title>InstallmentReport|Admin</title>
{% endblock %}
{% block css %}
{% endblock %}
{% block body %}

    <style>

        #UserTable_length {
            left: 20px;
            position: absolute;
        }

        #UserTable_filter {
            width: 50%;
            float: right;
        }

        .dt-buttons {
            position: absolute;
            left: 174px;
        }

        input[type=search] {
            width: 100px !important;
        }
    </style>

    <div class="ui right aligned basic  grid">
        <div class="sixteen wide column">
            <div class="ui  pointing secondary menu">
                <div style="cursor: pointer;" class="item active" data-tab="user"
                >Installments Report
                </div>
            </div>

            <div class="ui tab " data-tab="user">

                <div class="ui centered aligned basic padded grid">
                    <div class="row">
                        <div class="ui segment" style="width: 100%">
                            <div class="ui icon header">
                                <i class="cogs icon"></i>
                                Generate Installments Report
                            </div>
                            <div class="ui divider"></div>
                            <label class="ui tiny label purple">All reports are based on the installments list and
                                user.</label>

                            <div class="ui left aligned segment">
                                <div class="ui tiny form">
                                    <div class="five fields">
                                        <div class="field"></div>

                                        <div class="field">
                                            <label>Staff User</label>
                                            <select class="ui dropdown" id="status">

                                                <option value="All" selected>All</option>
                                                {% for user in users %}
                                                    <option value="{{ user.pk }}">{{ user.name|capfirst }}</option>
                                                {% endfor %}


                                            </select>
                                        </div>
                                        <div class="field">
                                            <label>Installment Start Date</label>
                                            <div class="ui calendar" id="rangestart">
                                                <div class="ui input left icon">
                                                    <i class="calendar icon"></i>
                                                    <input type="text" placeholder="Start" id="startDate">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label>Installment End Date</label>
                                            <div class="ui calendar" id="rangeend">
                                                <div class="ui input left icon">
                                                    <i class="calendar icon"></i>
                                                    <input type="text" placeholder="End" id="endDate">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="field"></div>
                                    </div>
                                </div>
                            </div>

                            <a onclick="GetReport()" class="ui primary button">Generate Now</a>
                        </div>

                    </div>

                </div>


            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>

        var today = new Date();
        $('#rangestart').calendar({
            initialDate: today.getDate() + '/' + (today.getMonth() + 1) + '/' + today.getFullYear(),
            monthFirst: false,
            type: 'day',
            endCalendar: $('#rangeend'),
            formatter: {
                date: function (date, settings) {
                    if (!date) return '';
                    var day = date.getDate();
                    var month = date.getMonth() + 1;
                    var year = date.getFullYear();
                    return day + '/' + month + '/' + year;
                }
            }
        });
        $('#rangeend').calendar({
            initialDate: today.getDate() + '/' + (today.getMonth() + 1) + '/' + today.getFullYear(),
            monthFirst: false,
            type: 'day',
            startCalendar: $('#rangestart'),
            formatter: {
                date: function (date, settings) {
                    if (!date) return '';
                    var day = date.getDate();
                    var month = date.getMonth() + 1;
                    var year = date.getFullYear();
                    return day + '/' + month + '/' + year;
                }
            }
        });


        function GetReport() {
            var status = $('#status').val();
            var startDate = $('#startDate').val();
            var endDate = $('#endDate').val();

            window.location.href = "{% url 'homeApp:download_installment_report' %}?status=" + status + '&startDate=' + startDate + '&endDate=' + endDate

        }

    </script>

{% endblock %}

home/templates/home/admin/adminHome.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,  user-scalable=0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    {% block title %}
        <title>Yelhoumee</title>
    {% endblock %}

    {% progressive_web_app_meta %}

    <link rel="icon" href="{% static 'sw/images/favicon.ico' %}" sizes="any">
    <link rel="apple-touch-icon" href="{% static 'sw/images/apple-touch-icon.png' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.8/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.8/dist/semantic.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/dataTables.semanticui.min.css">
    <script src="{% static 'sw/app.js' %}"></script>

    {% block css %}

    {% endblock %}
    <style>
        html {
            scroll-behavior: smooth;
        }

        .sidenav {
            height: 100%;
            width: 200px;
            position: fixed;
            z-index: 1;
            top: 40px;
            left: 0;
            background-color: #000000;
            overflow-x: hidden;
            padding-top: 10px;
        }

        .sidenav a {
            padding: 15px 12px 15px 16px;
            text-decoration: none;
            font-size: 18px;
            color: #818181;
            display: block;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .preloader {
            align-items: center;
            background: rgb(23, 22, 22);
            display: flex;
            height: 100vh;
            justify-content: center;
            left: 0;
            position: fixed;
            top: 0;
            transition: opacity 0.3s linear;
            width: 100%;
            z-index: 9999;
        }

        body ::-webkit-scrollbar {
            width: 6px;
        }

        .ui.vertical.menu.sidebar-menu {
            margin-top: 40px !important;
            max-height: calc(100% - 40px) !important;
            height: calc(100% - 40px) !important;
        }

        .ui.vertical.menu.sidebar-menu .item i.icon {
            float: left;
            margin: 0em 0.5em 0em 0em;
        }

        .main-content {
            margin-top: 40px;
        }

        @media (min-width: 768px) {
            .ui.vertical.menu.sidebar-menu {
                visibility: visible;
                -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
                width: 15rem !important;
            }

            .main-content {
                margin-left: 15rem;
            }

            .sidebar-menu-toggler {
                display: none !important;
            }
        }

        .custom_search {
            width: 100%;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }

        .custom_search:focus {
            width: 100%;
        }
        .bgColor{
            background-color: #232f3e!important;
        }
        .logoImg{
                width: 30px;
                height: 30px;
                margin: 5px;
                position: relative;
            left: 10px;
        }
    </style>

</head>

<body>
<!-- sidebar -->
<div class="ui sidebar inverted bgColor vertical menu sidebar-menu" id="sidebar">
    <div class="item">
        <div class="header">General</div>
        <div class="menu">
            <a class="item" href="{% url 'homeApp:admin_home' %}">
                <div>
                    <i class="tachometer alternate icon"></i>
                    Dashboard
                </div>
            </a>
        </div>
    </div>
    <div class="item">
        <div class="header">
            Sales
        </div>
        <div class="menu">
            <a class="item" href="#">
                <div><i class="users icon"></i>Customer List</div>
            </a>
            <a class="item" href="#">
                <div><i class="cart arrow down icon"></i>Sales List</div>
            </a>
            <a class="item" href="#">
                <div><i class="hand holding usd icon"></i>Installment List</div>
            </a>
        </div>
    </div>
    <div class="item">
        <div class="header">
            Purchase
        </div>
        <div class="menu">
            <a class="item" href="{% url 'homeApp:purchase_list' %}">
                <div><i class="cash register icon"></i>Purchase List</div>
            </a>
            <a class="item" href="{% url 'homeApp:product_list' %}">
                <div><i class="product hunt icon"></i>Products List</div>
            </a>
            <a class="item" href="{% url 'homeApp:supplier_add' %}">
                <div><i class="people carry icon"></i>Supplier List</div>
            </a>

        </div>
    </div>

    <div class="item">
        <div class="header">
            Staff
        </div>
        <div class="menu">
            <a class="item" href="{% url 'homeApp:user_list' %}">
                <div><i class="user tie icon"></i>User List</div>
            </a>

        </div>
    </div>
    <div class="item">
        <div class="header">
            Profile
        </div>
        <div class="menu">
            <a class="item" href="#">
                <div><i class="user icon"></i>My Profile</div>
            </a>
            <a class="item" href="{% url 'homeApp:logout' %}">
                <div><i class="sign out alternate icon"></i>Logout</div>
            </a>
        </div>
    </div>

    <div class="ui segment bgColor inverted">
        <div class="ui tiny olive inverted progress">
            <div class="bar" style="width: 54%"></div>
            <div class="label">Developed By Ziva Infotech</div>
        </div>

        <div class="ui tiny teal inverted progress">
            <div class="bar" style="width:78%"></div>
            <div class="label">v 0.9.5</div>
        </div>
    </div>
</div>

<!-- sidebar -->
<!-- top nav -->

<nav class="ui top fixed inverted bgColor menu">
    <div class="left menu">
        <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
            <i class="sidebar icon"></i>
        </a>
         <img class="logo logoImg" src="{% static 'sw/images/icon-192.png' %}">
        <a href="#" class="header item">

            Yelhoumee
        </a>
    </div>

    <div class="right menu">
        <div class="ui dropdown item">
            <i class="user cirlce icon"></i>
            <div class="menu">
                <a href="#" class="item">
                    <i class="info circle icon"></i> Profile</a
                >
                <a href="#" class="item">
                    <i class="wrench icon"></i>
                    Settings</a
                >
                <a href="{% url 'homeApp:logout' %}" class="item">
                    <i class="sign out alternate icon"></i>
                    Logout
                </a>
            </div>
        </div>
    </div>
</nav>

<!-- top nav -->

<div class="pusher">

    <div class="main-content">
        {% block body %}
            <div class="ui segment">
                <div class="ui breadcrumb">
                    <div class="active section">Dashboard</div>
                </div>
            </div>
            <div class="ui grid stackable padded">
                <div class="four wide computer eight wide tablet sixteen wide mobile column">
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="ui right floated header red">
                                <i class="icon shopping cart"></i>
                            </div>
                            <div class="header">
                                <div class="ui red header">
                                    3958
                                </div>
                            </div>
                            <div class="meta">
                                orders
                            </div>
                            <div class="description">
                                Elliot requested permission to view your contact details
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <div class="ui red button">More Info</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="four wide computer eight wide tablet sixteen wide mobile column">
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="ui right floated header green">
                                <i class="icon clock"></i>
                            </div>
                            <div class="header">
                                <div class="ui header green">57.6%</div>
                            </div>
                            <div class="meta">
                                Time
                            </div>
                            <div class="description">
                                Elliot requested permission to view your contact details
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <div class="ui green button">More Info</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="four wide computer eight wide tablet sixteen wide mobile column">
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="ui right floated header teal">
                                <i class="icon briefcase"></i>
                            </div>
                            <div class="header">
                                <div class="ui teal header">3112</div>
                            </div>
                            <div class="meta">
                                Saves
                            </div>
                            <div class="description">
                                Elliot requested permission to view your contact details
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <div class="ui teal button">More Info</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="four wide computer eight wide tablet sixteen wide mobile column">
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="ui right floated header purple">
                                <i class="icon trophy"></i>
                            </div>
                            <div class="header">
                                <div class="ui purple header">9805</div>
                            </div>
                            <div class="meta">
                                Views
                            </div>
                            <div class="description">
                                Elliot requested permission to view your contact details
                            </div>
                        </div>
                        <div class="extra content">
                            <div class="ui two buttons">
                                <div class="ui purple button">More Info</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        {% endblock %}
    </div>


</div>
<div class="preloader">
    <div class="ui active dimmer">
        <div class="ui medium text loader">Loading</div>
    </div>
</div>


<script src="https://frontendfunn.github.io/semantic-ui-admin-dashboard-template/js/script.js"></script>

<script>
    $('.menu .item').tab();
    $(window).on("load", function () {
        $(".preloader").fadeOut(50);
    });

    function showLoading() {
        $('#saveBtn').css('display', 'none');
        $('#saveBtnLoad').css('display', '');

    }

    function hideLoading() {
        $('#saveBtn').css('display', '');
        $('#saveBtnLoad').css('display', 'none');

    }

</script>
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.4/js/dataTables.semanticui.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.semanticui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>

{% block js %}
    <script>

    </script>

{% endblock %}
</body>
</html>