home/urls.py
from django.urls import path
from .views import *
from .apiView import *

urlpatterns = [
    # pages
    path('home/', homepage, name='homepage'),
    path('', loginPage, name='loginPage'),
    path('logout/', user_logout, name='logout'),
    path('postLogin/', postLogin, name='UserLogin'),

    # collection
    path('collection_home/', collection_home, name='collection_home'),
    path('customer_list_admin/', customer_list_admin, name='customer_list_admin'),
    path('customer_list/', customer_list, name='customer_list'),
    path('customer_add/', customer_add, name='customer_add'),
    path('customer_add_admin/', customer_add_admin, name='customer_add_admin'),
    path('sales_add/', sales_add, name='sales_add'),
    path('sales_add_admin/', sales_add_admin, name='sales_add_admin'),
    path('sales_edit_admin/<int:id>/', sales_edit_admin, name='sales_edit_admin'),
    path('sales_list/', sales_list, name='sales_list'),
    path('sales_list_admin/', sales_list_admin, name='sales_list_admin'),
    path('document_list_admin/', document_list_admin, name='document_list_admin'),
    path('report_admin/', report_admin, name='report_admin'),
    path('installment_report_admin/', installment_report_admin, name='installment_report_admin'),

    path('customer_detail/<int:id>/', customer_detail, name='customer_detail'),
    path('customer_detail_admin/<int:id>/', customer_detail_admin, name='customer_detail_admin'),
    path('customer_edit_admin/<int:id>/', customer_edit_admin, name='customer_edit_admin'),
    path('sales_detail/<int:id>/', sales_detail, name='sales_detail'),
    path('installment_list/', installment_list, name='installment_list'),
    path('my_profile/', my_profile, name='my_profile'),

    # admin
    path('my_profile_admin/', my_profile_admin, name='my_profile_admin'),
    path('admin_home/', admin_home, name='admin_home'),
    path('user_list/', user_list, name='user_list'),
    path('product_list/', product_list, name='product_list'),
    path('purchase_list/', purchase_list, name='purchase_list'),
    path('purchase_add/', purchase_add, name='purchase_add'),
    path('supplier_add/', supplier_add, name='supplier_add'),
    path('installment_list_admin/', installment_list_admin, name='installment_list_admin'),
    path('sales_detail_admin/<int:id>/', sales_detail_admin, name='sales_detail_admin'),

    path('login_logout_report_admin/', login_logout_report_admin, name='login_logout_report_admin'),

    # api Staff
    path('api/add_staff_api/', add_staff_api, name='add_staff_api'),
    path('api/delete_staff_user/', delete_staff_user, name='delete_staff_user'),
    path('api/get_staff_user_detail/', get_staff_user_detail, name='get_staff_user_detail'),
    path('api/edit_staff_api/', edit_staff_api, name='edit_staff_api'),
    path('api/StaffUserListJson/', StaffUserListJson.as_view(), name='StaffUserListJson'),

    # api Product
    path('api/list_product_api/', list_product_api, name='list_product_api'),
    path('api/add_product_api/', add_product_api, name='add_product_api'),
    path('api/delete_product/', delete_product, name='delete_product'),
    path('api/get_product_detail/', get_product_detail, name='get_product_detail'),
    path('api/edit_product_api/', edit_product_api, name='edit_product_api'),
    path('api/ProductListJson/', ProductListJson.as_view(), name='ProductListJson'),

    # api Supplier
    path('api/add_supplier_api/', add_supplier_api, name='add_supplier_api'),
    path('api/delete_supplier/', delete_supplier, name='delete_supplier'),
    path('api/get_supplier_detail/', get_supplier_detail, name='get_supplier_detail'),
    path('api/edit_supplier_api/', edit_supplier_api, name='edit_supplier_api'),
    path('api/SupplierListJson/', SupplierListJson.as_view(), name='SupplierListJson'),

    # api purchase

    path('api/add_purchase_api/', add_purchase_api, name='add_purchase_api'),
    path('api/delete_purchase/', delete_purchase, name='delete_purchase'),
    path('api/get_purchase_detail/<int:id>/', get_purchase_detail, name='get_purchase_detail'),
    path('api/PurchaseListJson/', PurchaseListJson.as_view(), name='PurchaseListJson'),

    # api Customer

    path('api/delete_customer_api/', delete_customer_api, name='delete_customer_api'),
    path('api/list_customer_api/', list_customer_api, name='list_customer_api'),
    path('api/add_customer_api/', add_customer_api, name='add_customer_api'),
    path('api/edit_customer_api/', edit_customer_api, name='edit_customer_api'),
    path('api/CustomerListByUserJson/', CustomerListByUserJson.as_view(), name='CustomerListByUserJson'),
    path('api/CustomerListAdminJson/', CustomerListAdminJson.as_view(), name='CustomerListAdminJson'),

    # sales
    path('api/delete_sale_api/', delete_sale_api, name='delete_sale_api'),
    path('api/add_sales_api/', add_sales_api, name='add_sales_api'),
    path('api/add_sales_admin_api/', add_sales_admin_api, name='add_sales_admin_api'),
    path('api/edit_sales_admin_api/', edit_sales_admin_api, name='edit_sales_admin_api'),
    path('api/list_sales_api/', list_sales_api, name='list_sales_api'),
    path('api/change_sales_status/', change_sales_status, name='change_sales_status'),
    path('api/SalesListByUserJson/', SalesListByUserJson.as_view(), name='SalesListByUserJson'),
    path('api/SalesListAdminJson/', SalesListAdminJson.as_view(), name='SalesListAdminJson'),

    # installments
    path('api/InstallmentListByAdminJson/', InstallmentListByAdminJson.as_view(), name='InstallmentListByAdminJson'),
    path('api/InstallmentListByUserJson/', InstallmentListByUserJson.as_view(), name='InstallmentListByUserJson'),
    path('api/delete_installment_api/', delete_installment_api, name='delete_installment_api'),
    path('api/get_installment_detail/', get_installment_detail, name='get_installment_detail'),
    path('api/add_installment_api/', add_installment_api, name='add_installment_api'),
    path('api/add_installment_remark_api/', add_installment_remark_api, name='add_installment_remark_api'),
    path('api/add_new_installment_api/', add_new_installment_api, name='add_new_installment_api'),
    path('api/edit_installment_api/', edit_installment_api, name='edit_installment_api'),

    # report dashboard
    path('api/get_collection_user_report_api/', get_collection_user_report_api, name='get_collection_user_report_api'),
    path('api/get_admin_report_api/', get_admin_report_api, name='get_admin_report_api'),
    path('api/get_last_three_days_collection_report_for_admin_api/',
         get_last_three_days_collection_report_for_admin_api,
         name='get_last_three_days_collection_report_for_admin_api'),
    path('api/get_last_three_days_collection_report_for_user_api/', get_last_three_days_collection_report_for_user_api,
         name='get_last_three_days_collection_report_for_user_api'),
    path('api/get_daily_collections_by_staff/', get_daily_collections_by_staff, name='get_daily_collections_by_staff'),

    # documents
    path('api/add_document_api/', add_document_api, name='add_document_api'),
    path('api/delete_document/', delete_document, name='delete_document'),
    path('api/get_document_detail/', get_document_detail, name='get_document_detail'),
    path('api/edit_document_api/', edit_document_api, name='edit_document_api'),
    path('api/DocumentListAdminJson/', DocumentListAdminJson.as_view(), name='DocumentListAdminJson'),

    # login and logout
    path('api/LoginLogoutListAdminJson/', LoginLogoutListAdminJson.as_view(), name='LoginLogoutListAdminJson'),

    # change password
    path('api/change_password_api/', change_password_api, name='change_password_api'),

    # report Downloads
    path('download_sales_report/', download_sales_report, name='download_sales_report'),
    path('download_installment_report/', download_installment_report, name='download_installment_report'),


    path('compare_money_api/', compare_money_api, name='compare_money_api'),

]

pro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='homeApp')),
    path('admin/', admin.site.urls),
    path('activate/', include(('activation.urls', 'activation'), namespace='activationApp')),
    path('', include('pwa.urls')),
    # path('', include('home.urls', namespace='homeApp')),
    # path('activation/', include('activation.urls', namespace='activationApp')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/templates/home/collection/profile.html
{% extends 'home/collection/indexCollection.html' %}
{% load static %}

{% block title %}
    <title>My Profile</title>
{% endblock %}
{% block css %}

{% endblock %}
{% block body %}
    <div class="ui right aligned basic  grid">
        <div class="sixteen wide column">
            <div class="ui  pointing secondary menu">
                <div style="cursor: pointer;" class="item active" data-tab="user"
                >My Profile
                </div>
            </div>

            <div class="ui tab " data-tab="user">
        <div style=" position: absolute;right: 1.5rem;top: 18px;">
                    <button class="ui green mini plus button right" onclick="showUserModal()">
                        <i class="plus square outline icon"></i>
                        Change Password
                    </button>
                </div>
                <div class="row" style="padding-left: 5px; padding-right: 5px">
                    <div class="ui placeholder segment" style="width: 100%;">
                        {% comment %}
            <a href="/ecom/editAccount/" class="editbtn"><i class="edit icon"></i></a>
{% endcomment %}
                        <div class="ui icon header">
                            <div class="inline ">
                                <img class="ui medium circular image tiny centered" id="cImg"
                                     src="{{ instance.photo.medium.url }}">
                            </div>
                            <span id="Name">{{ instance.name|capfirst }} </span>
                        </div>
                        <div class="inline">
                            <span id="username" class="ui text medium grey">{{ instance.username }}</span>
                        </div>
                        <div class="inline">
                            <span id="Phone">{{ instance.phone }}</span>
                        </div>
                        <div class="inline">
                            <span id="address" class="ui text large grey">{{ instance.address|capfirst }} </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


                    <div class="ui tiny modal" id="myModalUser">
                        <i class="close icon"></i>
                        <div class="header">
                            Change Password
                        </div>
                        <div class="content">

                            <form class="ui tiny form" id="addForm">{% csrf_token %}

                                  <div class="one required fields">
                                    <div class="sixteen wide field">
                                        <label>New Password</label>
                                        <input type="password" name="NewPassword" placeholder="New Password" id="newPassword">
                                    </div>

                                </div>
                                 <div class="one required fields">
                                    <div class="sixteen wide field">
                                        <label>Confirm Password</label>
                                        <input type="password" name="confirmPassword" placeholder="Confirm Password" id="confirmPassword">
                                    </div>

                                </div>

                            </form>

                            <div class="actions" style="padding-top: 20px; padding-bottom: 20px ;float: right">
                                <div class="ui cancel button">Cancel</div>
                                <button class="ui right labeled icon button green" onclick="changePassword()">
                                    Submit
                                    <i class="checkmark icon"></i>
                                </button>
                            </div>
                        </div>
                    </div>
{% endblock %}


{% block js %}
    <script>

        function showUserModal() {
            $('#myModalUser').modal('show');
        }
             function changePassword() {
            var pass = $('#newPassword').val();
            var passc = $('#confirmPassword').val();


            if (pass === '' || passc === "") {
                 $('body')
                    .toast({
                        class: 'orange',
                        message: '* fields are required.'
                    })
                ;

            }

            else {
                if (pass !== passc) {
                      $('body')
                    .toast({
                        class: 'orange',
                        message: 'Password not matched.'
                    })
                ;
                }
                else if (pass.length < 8) {
                      $('body')
                    .toast({
                        class: 'orange',
                        message: 'Password should be at least 8 characters long.'
                    })
                ;

                }
                else {
                     var csrfmiddlewaretoken = $("input[name='csrfmiddlewaretoken']").val();

                data = new FormData();
                data.append('password', pass);


                data.append('csrfmiddlewaretoken', csrfmiddlewaretoken);


                $.ajax({
                    type: 'post',
                    url: '{% url "homeApp:change_password_api" %}',
                    data: data,
                    contentType: false,
                    cache: false,
                    processData: false,


                    success: function (response) {
                        if (response.message === 'success') {
                            $('body')
                                .toast({
                                    class: 'success',
                                    message: 'Password changed Successfully.'
                                })
                            ;


                            $('#addForm').trigger('reset');
                            $('#myModalUser').modal('toggle');
                        } else {
                            $('body')
                                .toast({
                                    class: 'error',
                                    message: 'An error occurred !'
                                })
                            ;

                        }

                        return response;
                    },
                    error: function () {
                        $('body')
                            .toast({
                                class: 'error',
                                message: 'An error occurred !'
                            })
                        ;


            }
           });
            }
            }
             }



    </script>
{% endblock %}

home/templates/home/collection/salesListByStaff.html
{% extends 'home/collection/indexCollection.html' %}
{% load static %}
{% block title %}
    <title>SalesList|Collection</title>
{% endblock %}
{% block css %}
{% endblock %}
{% block body %}

    <style>

        #UserTable_length {
            left: 20px;
            position: absolute;
        }

        #UserTable_filter {
            width: 50%;
            float: right;
        }

        .dt-buttons {
            position: absolute;
            left: 174px;
        }

        input[type=search] {
            width: 100px !important;
        }
    </style>

    <div class="ui right aligned basic  grid">
        <div class="sixteen wide column">
            <div class="ui  pointing secondary menu">
                <div style="cursor: pointer;" class="item active" data-tab="user"
                >Sales List
                </div>
                <div style=" position: absolute;right: 1.5rem;top: 18px;">
                    <a href="{% url 'homeApp:sales_add' %}" class="ui green mini plus button right">
                        <i class="plus square outline icon"></i>
                        Add Sale
                    </a>
                </div>
            </div>

            <div class="ui tab " data-tab="user">

                <div class="row" style="padding-left: 5px; padding-right: 5px">
                    <div class="wide">
                        <div class="ui internally grid">

                            <div class="sixteen left aligned wide column">
                                <div class="ui form">
                                    <form class="ui tiny form">

                                        <div class="field">


                                            <label><i class="calendar alternate icon"></i>Filter By Date Range</label>

                                            <div class="three fields">
                                                <div class="four wide mobile field">
                                                    <div class="ui calendar" id="rangestart" style="width: 50%">
                                                        <div class="ui input left icon">
                                                            <input class="" type="text" placeholder="Start Date"
                                                                   style="width:100%;"
                                                                   id="startDateF">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="four wide mobile field">
                                                    <div class="ui calendar" id="rangeend" style="width: 50%">
                                                        <div class="ui input left icon">
                                                            <input class="" type="text" placeholder="End Date"
                                                                   style="width:100%;"
                                                                   id="endDateF">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="eight wide field">
                                                    <div class="ui calendar" id="rangeend">
                                                        <div class="ui input left icon">
                                                            <button class="ui tiny active button" type="button"
                                                                    onclick="filterDetails()">
                                                                <i class="funnel dollar icon"></i>
                                                                Search
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                            </div>

                        </div>

                        <table class="ui unstackable small  sortable celled very nowrap very compact table"
                               id="UserTable"
                               style="margin-top: 5px;width: 100%">
                            <thead>
                            <tr>
                                <th>Photo</th>
                                <th>SaleID</th>
                                <th>Customer Name</th>
                                <th>Product Name</th>
                                <th>Advance(₹)</th>
                                <th>Tenure</th>
                                <th>EMI(₹)</th>
                                <th>Total(₹)</th>
                                <th>Paid(₹)</th>
                                <th>ISD</th>
                                <th>Added On</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="ui basic modal custom" id="deleteUser">
                    <div class="ui icon header">
                        <i class="archive icon"></i>
                        User Details will be Deleted
                    </div>
                    <div class="content">
                        <p style="text-align: center">The User will be deleted, are you sure to delete this User?</p>
                    </div>
                    <div class="actions">
                        <div class="ui red basic cancel inverted button">
                            <i class="remove icon"></i>
                            No
                        </div>
                        <input type="hidden" id="UserID">
                        <div class="ui green ok inverted button" onclick="deleteUser()">
                            <i class="checkmark icon"></i>
                            Yes
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

    <div class="ui mini modal" id="imgModal">
        <i class="close icon"></i>
        <div class="header">Image Viewer</div>
        <div class="image content aligned center">
            <img class="image" id="imageLoad">
            <div class="description">
                <p></p>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>

        var today = new Date();
        $('#rangestart').calendar({
            initialDate: today.getDate() + '/' + (today.getMonth() + 1) + '/' + today.getFullYear(),
            monthFirst: false,
            type: 'date',
            endCalendar: $('#rangeend'),
            formatter: {
                date: function (date, settings) {
                    if (!date) return '';
                    var day = date.getDate();
                    var month = date.getMonth() + 1;
                    var year = date.getFullYear();
                    return day + '/' + month + '/' + year;
                }
            }
        });
        $('#rangeend').calendar({
            initialDate: today.getDate() + '/' + (today.getMonth() + 1) + '/' + today.getFullYear(),
            monthFirst: false,
            type: 'date',
            startCalendar: $('#rangestart'),
            formatter: {
                date: function (date, settings) {
                    if (!date) return '';
                    var day = date.getDate();
                    var month = date.getMonth() + 1;
                    var year = date.getFullYear();
                    return day + '/' + month + '/' + year;
                }
            }
        });


        var userTab;


        // user Details

        userTab = $('#UserTable').DataTable({
            dom: 'Blfrtip',
            "scrollY": "350px",
            "scrollX": true,
            fixedColumns: {
                left: 2,
                right: 1
            },
            buttons: [{
                extend: 'excel',
                exportOptions: {
                    columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
                }
            }
                {% comment %}      , {
                          extend: 'print',
                          exportOptions: {
                               columns: [1, 2, 3, 4, 5, 6, 7, 8]
                          }
                      }{% endcomment %}
            ],
            "columnDefs": [
                {"name": "deliveryPhoto", "targets": 0, "orderable": false},
                {"name": "saleNo", "targets": 1, "orderable": true},
                {"name": "customerName", "targets": 2, "orderable": true},
                {"name": "productName", "targets": 3, "orderable": true},
                {"name": "advancePaid", "targets": 4, "orderable": true},
                {"name": "tenureInMonth", "targets": 5, "orderable": true},
                {"name": "emiAmount", "targets": 6, "orderable": true},
                {"name": "totalAmount", "targets": 7, "orderable": true},
                {"name": "amountPaid", "targets": 8, "orderable": true},
                {"name": "installmentStartDate", "targets": 9, "orderable": true},
                {"name": "datetime", "targets": 10, "orderable": true},
                {"name": "action", "targets": 11, "orderable": false},

            ],
            aaSorting: [[10, 'desc']],
            "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
            "pageLength": 10,
            "processing": true,
            "serverSide": true,
            "ajax": "{% url 'homeApp:SalesListByUserJson' %}"
        });


        function delUser(id) {
            $('#deleteUser')
                .modal('show')
            ;
            $('#UserID').val(id)
        }

        function deleteUser() {
            var id = $('#UserID').val();
            var formdata = new FormData();
            formdata.append('userID', id);

            $.ajax({
                url: "{% url 'homeApp:delete_staff_user' %}",
                type: "post",
                data: formdata,
                contentType: false,
                cache: false,
                processData: false,

                success: function (response) {
                    if (response.message === 'success') {
                        $('body')
                            .toast({
                                class: 'success',
                                message: 'User Detail Deleted Successfully.'
                            })
                        ;


                        userTab.ajax.reload();
                    } else {
                        $('body')
                            .toast({
                                class: 'error',
                                message: 'An error occurred !'
                            })
                        ;

                    }

                    return response;
                },
                error: function () {
                    $('body')
                        .toast({
                            class: 'error',
                            message: 'An error occurred !'
                        })
                    ;
                }
            });

        }

        function filterDetails() {
            var startDate = $('#startDateF').val();
            var endDate = $('#endDateF').val();
            userTab.ajax.url('{% url 'homeApp:SalesListByUserJson' %}?startDate=' + startDate + '&endDate=' + endDate).load();

        }

        function showImgModal(img) {
            $('#imgModal').modal('show')
            $("#imageLoad").attr({"src": "" + img});
        }

    </script>

{% endblock %}